apiVersion: v1
kind: Service
metadata:
  name: node-backend-service
spec:
  type: NodePort
  selector:
    io.kompose.service: node-backend
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3010
      targetPort: 3010
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 31337