apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: node-backend
  name: node-backend
spec:
  ports:
  - name: "3010"
    port: 3010
    targetPort: 3010
  selector:
    io.kompose.service: node-backend
status:
  loadBalancer: {}
