apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: node-backend
  name: node-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: node-backend
    spec:
      containers:
      - args:
        - ./wait-for.sh
        - pg:5432
        - --
        - npm
        - start
        image: docker.io/bchall/node-backend-manual
        imagePullPolicy: ""
        name: node-backend
        ports:
        - containerPort: 3010
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
